In [4]:
%pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.10.8-cp313-cp313-win_amd64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.61.1-cp313-cp313-win_amd64.whl.metadata (116 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.4.9-cp313-cp313-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\32451\appdata\roaming\python\python313\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\32451\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\32451\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.8-cp313-cp313-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 8.1/8.1 MB 40.9 MB/s  0:00:00
Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.61.1-cp313-cp313-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 32.5 MB/s  0:00:00
Using cached kiwisolver-1.4.9-cp313-cp313-win_amd64.whl (73 kB)
Installing collected packages: kiwisolver, fonttools, cycler, contourpy, matplotlib

   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   ---------------------------------------- 5/5 [matplotlib]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.61.1 kiwisolver-1.4.9 matplotlib-3.10.8
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'c:\Users\32451\AppData\Local\Programs\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
%pip install pandas pyarrow

Requirement already satisfied: pandas in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (2.3.3)
Requirement already satisfied: pyarrow in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (22.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\32451\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\32451\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
%pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.5)
Requirement already satisfied: pandas>=1.2 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\32451\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\32451\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\32451\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\32451\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns


abm = pd.read_parquet("abm.parquet")
card = pd.read_parquet("card.parquet")
cheque = pd.read_parquet("cheque.parquet")
eft = pd.read_parquet("eft.parquet")
emt = pd.read_parquet("emt.parquet")
westernunion = pd.read_parquet("westernunion.parquet")
wire = pd.read_parquet("wire.parquet")

kyc_individual = pd.read_parquet("kyc_individual.parquet")
kyc_smallbusiness = pd.read_parquet("kyc_smallbusiness.parquet")
kyc_occupation_codes = pd.read_parquet("kyc_occupation_codes.parquet")
kyc_industry_codes = pd.read_parquet("kyc_industry_codes.parquet")

labels = pd.read_parquet("labels.parquet")

In [3]:
abm.head()

,transaction_id,customer_id,amount_cad,debit_credit,transaction_datetime,cash_indicator,country,province,city
0,ABM2411016110810,SYNID0104291988,300.0,D,2024-11-01 00:01,1,CA,BC,other
1,ABM2411013831558,SYNID0103664053,400.0,C,2024-11-01 00:03,1,CA,NS,other
2,ABM2411013725020,SYNID0106747172,400.0,D,2024-11-01 00:03,1,CA,BC,SURREY
3,ABM2411012851967,SYNID0106306354,320.0,D,2024-11-01 00:03,1,CA,BC,other
4,ABM2411018908251,SYNID0105732044,1000.0,D,2024-11-01 00:04,1,CA,BC,SURREY

In [4]:
card.head()

,transaction_id,customer_id,amount_cad,debit_credit,transaction_datetime,merchant_category,ecommerce_ind,country,province,city
0,CARD24110131109543,SYNID0102450742,13.35,D,2024-11-01 00:00:06,5812,1,CA,ON,None
1,CARD24110136178868,SYNID0105586872,6.05,D,2024-11-01 00:00:17,5968,1,None,None,other
2,CARD24110173783589,SYNID0107901560,81.40,C,2024-11-01 00:00:37,4816,0,CA,BC,None
3,CARD24110142566805,SYNID0107237475,3.20,D,2024-11-01 00:00:41,5814,0,CA,ON,MISSISSAUGA
4,CARD24110150346602,SYNID0109982946,356.03,D,2024-11-01 00:00:51,0,0,CA,AB,CALGARY

In [5]:
cheque.head()

,transaction_id,customer_id,amount_cad,debit_credit,transaction_datetime
0,CHQ241101366206,SYNID0200605005,813.90,C,2024-11-01
1,CHQ241101444612,SYNID0200217537,2851.12,C,2024-11-01
2,CHQ241101694712,SYNID0100054434,1602.20,D,2024-11-01
3,CHQ241101203093,SYNID0101266181,108.95,D,2024-11-01
4,CHQ241101799936,SYNID0200927212,4993.85,D,2024-11-01

In [6]:
eft.head()

,transaction_id,customer_id,amount_cad,debit_credit,transaction_datetime
0,EFT24110164807115,SYNID0200060564,304.58,D,2024-11-01 00:21:30
1,EFT24110104108345,SYNID0200905899,415.52,D,2024-11-01 00:21:38
2,EFT24110154542092,SYNID0200019640,1118.51,D,2024-11-01 00:22:38
3,EFT24110159355698,SYNID0200100125,230.83,D,2024-11-01 00:23:07
4,EFT24110155222970,SYNID0200253495,479.20,D,2024-11-01 00:23:18

In [7]:
emt.head()

,transaction_id,customer_id,amount_cad,debit_credit,transaction_datetime
0,EF3KBu4Y,SYNID0105556483,124.39,C,2024-11-01 00:00:00
1,EA6F2enW,SYNID0106445647,20.54,C,2024-11-01 00:00:08
2,Q7ZCC9kr,SYNID0105630694,2925.01,D,2024-11-01 00:00:09
3,iwp8M2vi,SYNID0108834681,738.38,D,2024-11-01 00:00:15
4,ZDCF4ZQM,SYNID0107079111,1557.58,D,2024-11-01 00:00:15

In [8]:
westernunion.head()

,transaction_id,customer_id,amount_cad,debit_credit,transaction_datetime
0,WU70151224,SYNID0101092403,228.71,D,2024-11-01 04:04:47
1,WU65427055,SYNID0106130686,127.78,D,2024-11-01 06:34:20
2,WU72536621,SYNID0101383552,123.21,D,2024-11-01 06:34:58
3,WU17761185,SYNID0107295306,977.30,D,2024-11-01 08:12:28
4,WU63304758,SYNID0105925328,968.66,D,2024-11-01 08:14:23

In [9]:
wire.head()

,transaction_id,customer_id,amount_cad,debit_credit,transaction_datetime
0,2411018567515752,SYNID0106350653,3070.13,C,2024-11-01
1,2411011617097052,SYNID0104386115,630.08,C,2024-11-01
2,2411017551414972,SYNID0200341758,21353.70,C,2024-11-01
3,2411011591775144,SYNID0107845453,1015.64,C,2024-11-01
4,2411015685130952,SYNID0108075156,128943.27,C,2024-11-01

In [17]:
kyc_individual.head(30)

,customer_id,country,province,city,gender,marital_status,occupation_code,income,birth_date,onboard_date
0,SYNID0100000167,CA,ON,TORONTO,None,Married,10019,48886.0,1972-01-30,2011-09-20
1,SYNID0100000431,CA,None,other,FEMALE,Married,72310,NaN,1988-03-20,2018-06-04
2,SYNID0100000485,CA,ON,BRAMPTON,FEMALE,Widowed,RETIRED,19998.0,1935-05-02,1997-07-12
3,SYNID0100000539,CA,None,other,MALE,Widowed,RETIRED,39417.0,1944-11-04,1985-05-14
4,SYNID0100000932,CA,ON,TORONTO,FEMALE,Married,RETIRED,34182.0,1963-09-14,2012-07-09
5,SYNID0100001185,CA,AB,EDMONTON,FEMALE,Married,UNEMPLOYED,29525.0,1958-04-21,2009-06-25
6,SYNID0100001300,CA,AB,CALGARY,FEMALE,Single,RETIRED,15277.0,1958-01-20,1992-08-04
7,SYNID0100001310,CA,None,other,FEMALE,Single,SELF_EMPLOYED,53501.0,1974-01-10,2015-09-28
8,SYNID0100001952,CA,ON,SUDBURY,FEMALE,Single,70010,NaN,1997-09-10,2014-12-28
9,SYNID0100002045,CA,ON,KINGSTON,MALE,None,RETIRED,56863.0,1958-09-24,2000-04-28
10,SYNID0100002163,CA,None,other,FEMALE,Married,RETIRED,118812.0,1948-11-20,2000-12-19
11,SYNID0100002187,CA,None,other,FEMALE,Single,UNEMPLOYED,8523.0,1986-05-21,2004-03-09
12,SYNID0100002198,CA,AB,LEDUC,FEMALE,Married,UNEMPLOYED,NaN,None,2022-12-03
13,SYNID0100002385,CA,ON,MISSISSAUGA,FEMALE,Single,OTHER,40359.0,1998-09-18,2017-10-28
14,SYNID0100002875,CA,None,other,FEMALE,Married,RETIRED,8962.0,1953-01-14,2011-01-23
15,SYNID0100003249,CA,None,other,MALE,Married,75200,42352.0,1992-10-28,2019-08-06
16,SYNID0100003319,CA,ON,BARRIE,MALE,Single,UNEMPLOYED,15.0,2007-04-14,None
17,SYNID0100003755,CA,ON,WOODBRIDGE,MALE,Unknown,STUDENT,NaN,1994-08-03,2023-07-17
18,SYNID0100004490,CA,BC,SURREY,MALE,Married,14100,49604.0,1992-08-19,2021-11-10
19,SYNID0100004580,CA,ON,ST CATHARINES,MALE,Single,63101,164821.0,1985-01-06,1996-04-07
20,SYNID0100004593,CA,ON,CARLETON PLACE,MALE,Married,UNEMPLOYED,19594.0,1970-11-10,2021-02-08
21,SYNID0100004629,CA,ON,LONDON,MALE,None,SELF_EMPLOYED,75937.0,1982-09-30,2000-04-23
22,SYNID0100004657,CA,ON,WINDSOR,FEMALE,Married,OTHER,36204.0,1980-03-29,2016-05-22
23,SYNID0100004837,CA,None,other,MALE,Married,RETIRED,62283.0,1956-04-12,1984-07-11
24,SYNID0100004848,CA,None,other,FEMALE,Unknown,STUDENT,NaN,2004-03-22,2024-09-19
25,SYNID0100005297,CA,ON,MISSISSAUGA,MALE,None,75200,115365.0,1975-01-18,2004-09-21
26,SYNID0100005641,CA,None,other,MALE,None,21321,131805.0,1970-02-02,2000-01-13
27,SYNID0100005686,CA,ON,SCARBOROUGH,MALE,Married,RETIRED,60670.0,1947-05-04,1992-09-18
28,SYNID0100005856,CA,ON,BRAMPTON,MALE,Married,RETIRED,16674.0,1930-11-24,1992-03-31
29,SYNID0100006155,CA,None,other,FEMALE,Married,OTHER,NaN,1959-11-29,1999-09-24

In [16]:
kyc_industry_codes.head(50)

    industry_code                                           industry
0             112                                       Cattle Farms
1             119                        Livestock Combination Farms
2             139                             Other Field Crop Farms
3             141                       Field Crop Combination Farms
4             171  Livestock, Field Crop and Horticultural Combin...
5             211                                Veterinary Services
6             219  Other Services Incidental to Livestock and Ani...
7             311                        Salt Water Fishing Industry
8             411         Logging Industry (Except Contract Logging)
9             511                         Forestry Services Industry
10            711    Conventional Crude Oil and Natural Gas Industry
11            919  Other Service Industries Incidental to Crude P...
12           1099              Other Food Products Industries n.e.c.
13           2499       Other Clothing and Apparel Industries n.e.c.
14           2819               Other Commercial Printing Industries
15           2839                        Other Publishing Industries
16           3081                              Machine Shop Industry
17           3099          Other Metal Fabricating Industries n.e.c.
18           3192  Construction and Mining Machinery and Material...
19           3199    Other Machinery and Equipment Industries n.e.c.
20           3999      Other Manufactured Products Industries n.e.c.
21           4011                              Single Family Housing
22           4013                             Residential Renovation
23           4021        Manufacturing and Light Industrial Building
24           4022                                Commercial Building
25           4112  Gas, Oil and Other Energy Related Structures (...
26           4113                              Gas and Oil Pipelines
27           4129                           Other Heavy Construction
28           4214                             Excavating and Grading
29           4219                                    Other Site Work
30           4224                     Concrete Pouring and Finishing
31           4226                        Rough and Framing Carpentry
32           4229                  Other Structural and Related Work
33           4231                                       Masonry Work
34           4232                                        Siding Work
35           4233                             Glass and Glazing Work
36           4235                                     Roof Shingling
37           4239                       Other Exterior Close-In Work
38           4241                                           Plumbing
39           4261                                    Electrical Work
40           4272                                       Drywall Work
41           4274                                   Finish Carpentry
42           4275                       Painting and Decorating Work
43           4276                             Terrazzo and Tile Work
44           4278                 Resilient Flooring and Carpet Work
45           4279                  Other Interior and Finishing Work
46           4299                            Other Trade Work n.e.c.
47           4411                   Project Management, Construction
48           4491                                    Land Developers
49           4499   Other Services Incidental to Construction n.e.c.

In [12]:
kyc_occupation_codes.head()

   occupation_code                               occupation_title
0                0  Legislative and senior management occupations
1            10010                             Financial managers
2            10011                       Human resources managers
3            10019         Other administrative services managers
4            10029               Other business services managers

In [13]:
kyc_smallbusiness.head()

,customer_id,country,province,city,industry_code,employee_count,sales,established_date,onboard_date
0,SYNID0200000024,CA,ON,BRAMPTON,9699,5.0,181876.0,2022-12-09,2022-12-26
1,SYNID0200000050,CA,ON,TORONTO,4214,1.0,250009.0,1991-02-24,1996-06-17
2,SYNID0200000104,CA,AB,EDMONTON,7215,2.0,217904.0,2011-06-20,None
3,SYNID0200000167,CA,None,other,8649,1.0,0.0,2024-02-20,2024-11-27
4,SYNID0200000345,CA,None,other,9861,NaN,NaN,2003-12-08,2003-12-18

In [14]:
labels.head()

       customer_id  label
0  SYNID0100000485      0
1  SYNID0100021236      0
2  SYNID0100036671      0
3  SYNID0100059315      0
4  SYNID0100060562      0

## Feature Engineering (Tony)

### rapid_outflow_ratio_24h

 = Total debits within 24h of cash deposits/ Total cash deposit amount

 Measures how much of deposited cash leaves the account within 24hrs. Higher ratio indicates the account is being used to quickly pass funds through rather than hold or spend them, which is typical in layering and money rule activity.

### emt_velocity_7d

= Number of EMT transactions in rolling 7-day

Counts how frequently the client uses email money transfer (EMT) within a short period. Unusually high digital transfer frequency suggests rapid movement of funds that may indicate mule networks or account cycling.

### income_transaction_gap_score

Monthly Total Credit = $\sum$(credits across ABM, EMT, EFT, WIRE, CHEQUE)

Declared Monthly Income = $\frac{\text{kyc income}}{12}$

Inme transaction gap score = Monthly Total Credit / Decalred Monthly Income

Comparing actual monthly inflows to the income declared in KYC records. A large gap indicates the client is receiving more money than their reported income supports, which may signal undeclared business activity or use of the account to receive thrid-party funds.

### cash_value_ratio

= $\frac{\text{Total ABM cash transactions}}{\text{Total transatcion amount across all channels}}$

Measures how much of the client's total activity is conducted in physical cash. Excessive reliance on cash to total account activity is inconsistent with most profiles with salaries and increases AML risk due to reduction in track.

### spending_income_ratio

- Monthly card Spend = $\sum$ (CARD debits)

= Monthly Card Spend/ Decalred Monthly Income.

Compares client spending to decalred income. A ratio substantially above 1 suggests the client is spending beyond reported means, which may indicate hidden income sources or financial stress masked by incoming suspicious funds.

### abm_withdrawal_zscore (optional)

 $$= \frac{\text{Client Average Withdrawal} - \mu_{peer}}{\sigma_{peer}}$$

 Within-group abm withdrawal zscore, peer indicates different occupation code or segment

 Identifying clients whose ATM withdrawals are significantly larger than peers with similar profiles. Large and repeated cash withdrawals can indicate cash structuring or conversion of electronic funds into untraceable form.

### small_cash_geo_entropy_30d (optional)

- It filters ABM cash deposits below a proxy threshold.

- Compute proportion of deposits per city:
$p_i = \frac{\text{deposits in city } i}{\text{Total small deposits}}$

- And then the entropy
 = $\sum p_i\log(p_i)$

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, average_precision_score
from sklearn.model_selection import train_test_split

## Preprocessing

In [19]:
# ----------------------------
# 0) Helpers: standardization
# ----------------------------
def _to_datetime(s):
    return pd.to_datetime(s, errors="coerce")

def standardize_tx(df, source, has_geo=False):
    """
    Expected columns (from your heads):
      transaction_id, customer_id, amount_cad, debit_credit, transaction_datetime
    Optional geo:
      country, province, city
    """
    out = df.copy()
    out["source"] = source
    out["transaction_datetime"] = _to_datetime(out["transaction_datetime"])
    out["amount_cad"] = pd.to_numeric(out["amount_cad"], errors="coerce")

    # Standardize direction
    # debit_credit: D = money OUT, C = money IN
    out["is_debit"] = out["debit_credit"].astype(str).str.upper().eq("D")
    out["is_credit"] = out["debit_credit"].astype(str).str.upper().eq("C")

    # Signed amount (+ inflow, - outflow)
    out["signed_amount"] = np.where(out["is_credit"], out["amount_cad"],
                             np.where(out["is_debit"], -out["amount_cad"], np.nan))

    keep_cols = ["transaction_id", "customer_id", "amount_cad", "signed_amount",
                 "debit_credit", "is_debit", "is_credit", "transaction_datetime", "source"]

    if has_geo:
        for c in ["country", "province", "city"]:
            if c in out.columns:
                keep_cols.append(c)

    out = out[keep_cols]
    return out


def shannon_entropy(values):
    """
    Entropy over a categorical series (e.g., city).
    Returns 0.0 if empty / single category.
    """
    if values is None or len(values) == 0:
        return 0.0
    vc = pd.Series(values).value_counts(dropna=True)
    if vc.sum() == 0 or len(vc) <= 1:
        return 0.0
    p = vc / vc.sum()
    return float(-(p * np.log(p)).sum())

In [24]:
# ----------------------------------------
# 1) Merge occupation + industry text
# ----------------------------------------

# Ensure string type
kyc_individual["occupation_code"] = kyc_individual["occupation_code"].astype(str)
kyc_occupation_codes["occupation_code"] = kyc_occupation_codes["occupation_code"].astype(str)

kyc_smallbusiness["industry_code"] = kyc_smallbusiness["industry_code"].astype(str)
kyc_industry_codes["industry_code"] = kyc_industry_codes["industry_code"].astype(str)

# Merge occupation title
kyc_ind = kyc_individual.merge(
    kyc_occupation_codes,
    on="occupation_code",
    how="left"
)

# Merge industry text
kyc_sb = kyc_smallbusiness.merge(
    kyc_industry_codes,
    on="industry_code",
    how="left"
)

# Employment status flags
kyc_ind["is_retired"] = (kyc_ind["occupation_code"].str.upper() == "RETIRED").astype(int)
kyc_ind["is_unemployed"] = (kyc_ind["occupation_code"].str.upper() == "UNEMPLOYED").astype(int)

In [ ]:

### NLP Clustering for occupation and industry text
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import MiniBatchKMeans

def cluster_unique_text(text_series, n_clusters=30):

    txt = (
        text_series.fillna("unknown")
        .astype(str)
        .str.lower()
        .str.replace(r"[^a-z\s]+", " ", regex=True)
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )

    unique_txt = txt.drop_duplicates().reset_index(drop=True)

    vectorizer = TfidfVectorizer(
        stop_words="english",
        max_features=800,
        ngram_range=(1,1),
        min_df=2,
        max_df=0.9
    )

    X = vectorizer.fit_transform(unique_txt)

    kmeans = MiniBatchKMeans(
        n_clusters=min(n_clusters, len(unique_txt)),
        random_state=42,
        batch_size=2048,
        n_init="auto"
    )

    clusters = kmeans.fit_predict(X)

    mapping = pd.DataFrame({
        "text": unique_txt,
        "cluster": clusters
    })

    final_clusters = txt.to_frame("text").merge(mapping, on="text", how="left")["cluster"].values

    return final_clusters

# Apply clustering
kyc_ind["occupation_sector_id"] = cluster_unique_text(
    kyc_ind["occupation_title"].fillna(kyc_ind["occupation_code"]),
    n_clusters=30
)

kyc_sb["industry_sector_id"] = cluster_unique_text(
    kyc_sb["industry"].fillna(kyc_sb["industry_code"]),
    n_clusters=25
)

In [26]:
# Standardize Transactions
def prepare_tx(df, source):
    df = df.copy()
    df["transaction_datetime"] = pd.to_datetime(df["transaction_datetime"], errors="coerce")
    df["amount_cad"] = pd.to_numeric(df["amount_cad"], errors="coerce")

    df["is_debit"] = df["debit_credit"].str.upper() == "D"
    df["is_credit"] = df["debit_credit"].str.upper() == "C"

    df["source"] = source

    return df

abm_tx = prepare_tx(abm, "ABM")
card_tx = prepare_tx(card, "CARD")
emt_tx = prepare_tx(emt, "EMT")
cheque_tx = prepare_tx(cheque, "CHEQUE")
eft_tx = prepare_tx(eft, "EFT")
wu_tx = prepare_tx(westernunion, "WESTERNUNION")
wire_tx = prepare_tx(wire, "WIRE")

tx_all = pd.concat([
    abm_tx, card_tx, emt_tx,
    cheque_tx, eft_tx, wu_tx, wire_tx
], ignore_index=True)

## FE - Feature Engineering codes

In [27]:
def rapid_outflow_ratio_24h(abm_tx, tx_all):

    deposits = abm_tx[
        (abm_tx["cash_indicator"] == 1) &
        (abm_tx["is_credit"])
    ].copy()

    deposits = deposits.sort_values(["customer_id", "transaction_datetime"])

    outflows = tx_all[tx_all["is_debit"]].copy()
    outflows = outflows.sort_values(["customer_id", "transaction_datetime"])

    H = pd.Timedelta(hours=24)

    result = []

    for cust, dep in deposits.groupby("customer_id"):

        out = outflows[outflows["customer_id"] == cust]

        if out.empty:
            result.append((cust, 0.0))
            continue

        total_dep = dep["amount_cad"].sum()
        out_sum = 0

        for _, row in dep.iterrows():
            t = row["transaction_datetime"]
            window = out[
                (out["transaction_datetime"] >= t) &
                (out["transaction_datetime"] <= t + H)
            ]
            out_sum += window["amount_cad"].sum()

        ratio = out_sum / total_dep if total_dep > 0 else 0
        result.append((cust, ratio))

    return pd.DataFrame(result, columns=["customer_id", "rapid_outflow_ratio_24h"])

feat_rapid = rapid_outflow_ratio_24h(abm_tx, tx_all)

KeyboardInterrupt:

In [ ]:
emt_velocity = (
    emt_tx.groupby("customer_id")
    .size()
    .reset_index(name="emt_velocity_total")
)

In [ ]:
credits = tx_all[tx_all["is_credit"]]

monthly_credits = (
    credits
    .assign(month=credits["transaction_datetime"].dt.to_period("M"))
    .groupby(["customer_id","month"])["amount_cad"]
    .sum()
    .groupby("customer_id")
    .mean()
    .reset_index(name="avg_monthly_credit")
)

kyc_ind["declared_monthly_income"] = kyc_ind["income"] / 12

feat_income_gap = kyc_ind.merge(monthly_credits, on="customer_id", how="left")
feat_income_gap["income_transaction_gap"] = (
    feat_income_gap["avg_monthly_credit"] /
    feat_income_gap["declared_monthly_income"]
)

In [ ]:
cash_total = (
    abm_tx[abm_tx["cash_indicator"] == 1]
    .groupby("customer_id")["amount_cad"]
    .sum()
)

total_amount = tx_all.groupby("customer_id")["amount_cad"].sum()

feat_cash_ratio = (
    pd.DataFrame({
        "cash_total": cash_total,
        "total_amount": total_amount
    })
    .fillna(0)
    .reset_index()
)

feat_cash_ratio["cash_value_ratio"] = (
    feat_cash_ratio["cash_total"] /
    feat_cash_ratio["total_amount"]
)

In [ ]:
abm_withdraw = (
    abm_tx[abm_tx["is_debit"]]
    .groupby("customer_id")["amount_cad"]
    .mean()
    .reset_index(name="avg_abm_withdraw")
)

feat_abm = kyc_ind[["customer_id","occupation_sector_id"]].merge(
    abm_withdraw,
    on="customer_id",
    how="left"
)

feat_abm["abm_withdrawal_zscore"] = (
    feat_abm.groupby("occupation_sector_id")["avg_abm_withdraw"]
    .transform(lambda x: (x - x.mean()) / x.std())
)

In [ ]:
card_spend = (
    card_tx[card_tx["is_debit"]]
    .assign(month=card_tx["transaction_datetime"].dt.to_period("M"))
    .groupby(["customer_id","month"])["amount_cad"]
    .sum()
    .groupby("customer_id")
    .mean()
    .reset_index(name="avg_monthly_card_spend")
)

feat_spend = kyc_ind.merge(card_spend, on="customer_id", how="left")
feat_spend["spending_income_ratio"] = (
    feat_spend["avg_monthly_card_spend"] /
    feat_spend["declared_monthly_income"]
)

In [ ]:
from sklearn.metrics import average_precision_score
from sklearn.model_selection import train_test_split

def geo_entropy_threshold(abm_tx, labels):

    cash_dep = abm_tx[
        (abm_tx["cash_indicator"] == 1) &
        (abm_tx["is_credit"])
    ]["amount_cad"]

    percentiles = list(range(50,95,5)) + [97,99]
    candidates = [np.percentile(cash_dep, p) for p in percentiles]

    best_ap = -1
    best_T = None

    for T in candidates:

        small_dep = abm_tx[
            (abm_tx["cash_indicator"] == 1) &
            (abm_tx["is_credit"]) &
            (abm_tx["amount_cad"] < T)
        ]

        ent = (
            small_dep.groupby("customer_id")["city"]
            .apply(lambda x: -np.sum(
                (x.value_counts(normalize=True) *
                 np.log(x.value_counts(normalize=True)))
            ))
            .reset_index(name="geo_entropy")
        )

        df = labels.merge(ent, on="customer_id", how="left").fillna(0)

        ap = average_precision_score(df["label"], df["geo_entropy"])

        if ap > best_ap:
            best_ap = ap
            best_T = T

    return best_T

best_T = geo_entropy_threshold(abm_tx, labels)

In [ ]:
### Features Summarize Table

features = (
    labels
    .merge(feat_rapid, on="customer_id", how="left")
    .merge(emt_velocity, on="customer_id", how="left")
    .merge(feat_income_gap[["customer_id","income_transaction_gap"]], on="customer_id", how="left")
    .merge(feat_cash_ratio[["customer_id","cash_value_ratio"]], on="customer_id", how="left")
    .merge(feat_abm[["customer_id","abm_withdrawal_zscore"]], on="customer_id", how="left")
    .merge(feat_spend[["customer_id","spending_income_ratio"]], on="customer_id", how="left")
)

features.head()